services:
    laravel.app:
        image: ghcr.io/okenagod/knihozrout/laravel-app:latest
        container_name: laravel_app
        restart: always
        env_file: .env
        volumes:
            - production-app-storage:/var/www/html/storage
            - app-code:/var/www/html
            - ./google-auth.json:/var/www/html/google-auth.json
        networks:
            - backend

    # Webový server (Nginx)
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - "8080:80" # Port 8080 bude ten, který zadáš do NPM
        volumes:
            - app-code:/var/www/html:ro
            - production-app-storage:/var/www/html/storage:ro
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel.app
        networks:
            - backend
            - proxy_network

    # Databáze
    mysql:
        image: 'mysql:8.4'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - 'production-db-data:/var/lib/mysql'
        networks:
            - backend

networks:
    backend:
        driver: bridge
    proxy_network:
        external: true # Tato síť už existuje (vytvořili jsme ji pro NPM)

volumes:
    production-db-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /srv/volume/knihozrout/db
    production-app-storage:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /srv/volume/knihozrout/storage
    app-code: