name: deploy.yml

on:
  push:
    branches: [ "master" ] # Spustí se při každém pushi do main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.prod
          push: true
          tags: ghcr.io/${{ github.repository }}/laravel-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Musíme kód "stáhnout" i v tomto jobu, abychom měli přístup k souborům

      - name: Prepare compose file
        run: cp compose-prod.yaml compose.yaml

      - name: Copy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "compose.yaml"
          target: "/var/www"

      - name: Copy nginx config
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "serverconfig/nginx.conf"
          target: "/var/www"
          strip_components: 1

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            # 1. Stáhnout nový obraz a restartovat kontejnery
            docker compose pull
            docker compose up -d --force-recreate
            # 2. Spustit Laravel příkazy uvnitř běžícího kontejneru
            # Používáme -T (disable pseudo-tty), protože v CI prostředí není terminál
            docker compose exec -T laravel.app php artisan migrate --force
            docker compose exec -T laravel.app php artisan storage:link
            docker compose exec -T laravel.app php artisan config:cache
            docker compose exec -T laravel.app php artisan route:cache
            docker compose exec -T laravel.app php artisan view:cache
            # 3. Úklid starých obrazů kvůli místu na disku
            docker image prune -f
